type: task
# The name is optional, if not specified, generated randomly
name: test

# Using the official Axolotl's Docker image
image: winglian/axolotl-cloud:main-20240429-py3.11-cu121-2.2.1

# Required environment variables
# env:
#   - HF_TOKEN

# Commands of the task
commands:
  - uv sync
  - uv run test.py

resources:
  gpu:
    # 24GB or more VRAM
    memory: 24GB..
    # Two or more GPU
    count: 2..
