[project]
name = "power-estimation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.13.15",
    "pandas>=2.2.3",
    "pyarrow>=20.0.0",
]
