[project]
name = "AI-Hardcore-Hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.7.0",
    "numpy>=2.2.6",
    "pandas>=2.2.3",
    "torch>=2.7.0",
    "transformers>=4.52.4",
]
